// La collection : dix voitures, de la plus accessible à la plus prestigieuse.
// Chaque entrée alimente le studio (textes, fiche, caméras) et la conduite (performances).
// Les modèles 3D sont des assets CC0 (Quaternius, Kenney) repeints aux couleurs de chaque marque ;
// les silhouettes sont stylisées, les chiffres sont ceux des voitures réelles.

const Q = "assets/cars/";
const K = "assets/cars/kenney/";

export const CARS = [
  {
    id: "sandero",
    rank: 1,
    brand: "Dacia",
    model: "Sandero",
    tier: "Accessible",
    years: "2021 –",
    origin: "Mioveni, Roumanie",
    price: "≈ 12 000 €",
    tagline: "La voiture neuve la moins chère d'Europe, et la plus vendue aux particuliers.",
    lead: "Un seul objectif : l'essentiel, bien fait. Moteur trois cylindres, boîte manuelle, un coffre de 328 litres et rien qui ne serve pas tous les jours.",
    paint: "#2f6fd1",
    vehicle: { src: "assets/cars/real/sandero.glb", kind: "sketchfab", forward: "+z", length: 4.09, paintMaterial: "primary" },
    credit: { title: "Dacia Sandero 2018", author: "🇷🇴シRuletăシ🇷🇴", url: "https://sketchfab.com/3d-models/dacia-sandero-2018-8ee1188f4d694d4c9b648c8dd5b471da", license: "CC Attribution" },
    specs: { moteur: "3 cyl. 1,0 l turbo", puissance: "90 ch", couple: "160 Nm", zeroCent: "12,0 s", vmax: "175 km/h", poids: "1 050 kg", transmission: "Traction, manuelle 6" },
    sections: [
      { view: "aero", title: "Simplicité", text: "Pas de ligne décorative : les flancs sont plans, la calandre est peinte, les optiques LED sont le seul geste. Chaque pièce a un prix, chaque prix est compté.", facts: [["Coffre", "328 l"], ["Longueur", "4,09 m"]] },
      { view: "wheel", title: "Roues et suspension", text: "Jantes de 15 pouces en acier avec enjoliveurs, pneus à taille haute : le confort avant tout sur des routes qui ne sont pas toujours parfaites.", facts: [["Jantes", "15 pouces"], ["Garde au sol", "163 mm"]] },
      { view: "rear", title: "Moteur", text: "Le TCe 90, trois cylindres turbo partagé avec la Clio. Sobre, discret, et assez de couple bas pour ne pas avoir à rétrograder en ville.", facts: [["Consommation", "5,3 l/100 km"], ["CO₂", "120 g/km"]] },
      { view: "top", title: "Habitacle", text: "Un écran de 8 pouces qui reflète simplement le téléphone, des commandes physiques pour la clim, cinq vraies places. Rien à apprendre.", facts: [["Places", "5"], ["Écran", "8 pouces"]] },
    ],
    drive: { vmax: 175, accel: 5.5, brake: 9, grip: 0.85, mass: 1050, redline: 6000 },
  },
  {
    id: "clio",
    rank: 2,
    brand: "Renault",
    model: "Clio",
    tier: "Citadine",
    years: "2019 –",
    origin: "Bursa, Turquie",
    price: "≈ 19 000 €",
    tagline: "Trente ans de best-seller français, cinquième génération.",
    lead: "La citadine qui a défini la catégorie en 1990. Aujourd'hui hybride E-Tech, avec une finition qui regarde une gamme au-dessus.",
    paint: "#1e3fbf",
    vehicle: { src: "assets/cars/real/clio.glb", kind: "sketchfab", forward: "-z", length: 4.05, paintMaterial: "Color_I08" },
    credit: { title: "2020 Renault Clio", author: "tonielpro520", url: "https://sketchfab.com/3d-models/2020-renault-clio-4c528fefa4154004bbc6305faf71836c", license: "CC Attribution" },
    specs: { moteur: "4 cyl. 1,6 l hybride E-Tech", puissance: "145 ch", couple: "205 Nm", zeroCent: "9,3 s", vmax: "180 km/h", poids: "1 300 kg", transmission: "Traction, multimode" },
    sections: [
      { view: "aero", title: "Dessin", text: "Le capot est nervuré, les optiques en C sont devenues la signature de la marque. Un dessin tendu qui vieillit bien.", facts: [["Cx", "0,32"], ["Longueur", "4,05 m"]] },
      { view: "wheel", title: "Châssis", text: "Plateforme CMF-B partagée avec la Sandero et le Captur, mais réglée plus ferme : la Clio reste la référence de la catégorie sur route sinueuse.", facts: [["Jantes", "17 pouces"], ["Empattement", "2,58 m"]] },
      { view: "rear", title: "Hybride", text: "Une boîte à crabots sans embrayage héritée de la Formule 1, deux moteurs électriques : en ville, 80 % du temps se fait moteur essence coupé.", facts: [["Consommation", "4,2 l/100 km"], ["Batterie", "1,2 kWh"]] },
      { view: "top", title: "Habitacle", text: "Écran vertical de 9,3 pouces, sellerie recyclée, planche de bord souple. La qualité perçue a fait un bond entre la quatrième et la cinquième génération.", facts: [["Écran", "9,3 pouces"], ["Coffre", "301 l"]] },
    ],
    drive: { vmax: 180, accel: 7, brake: 10, grip: 0.9, mass: 1300, redline: 6500 },
  },
  {
    id: "golf",
    rank: 3,
    brand: "Volkswagen",
    model: "Golf GTI",
    tier: "Compacte sportive",
    years: "2013 – 2020",
    origin: "Wolfsburg, Allemagne",
    price: "≈ 38 000 €",
    tagline: "L'inventrice de la compacte sportive, septième génération.",
    lead: "En 1976, la première GTI a créé une catégorie. La Mk7 en est la version la plus équilibrée : 230 ch, un différentiel avant piloté et une finition que la concurrence n'a jamais rattrapée.",
    paint: "#e3e5e8",
    vehicle: { src: "assets/cars/real/golf.glb", kind: "sketchfab", forward: "+z", length: 4.27, paintMaterial: "vVolkswagen_GolfGTI_2014Paint_Material1" },
    credit: { title: "2014 Volkswagen Golf GTI Mk7", author: "Ddiaz Design", url: "https://sketchfab.com/3d-models/2014-volkswagen-golf-gti-mk7-93f2b79c56c14b269fbe914205c4712e", license: "CC Attribution-NonCommercial-ShareAlike" },
    specs: { moteur: "4 cyl. 2,0 l TSI", puissance: "230 ch", couple: "350 Nm", zeroCent: "6,4 s", vmax: "250 km/h", poids: "1 364 kg", transmission: "Traction, DSG 6" },
    sections: [
      { view: "aero", title: "Le liseré rouge", text: "La calandre soulignée de rouge, la jante à rayons, le tissu à carreaux : les codes de 1976 sont tous là, tenus par un dessin d'une sobriété absolue. La GTI n'a jamais eu besoin de crier.", facts: [["Cx", "0,30"], ["Longueur", "4,27 m"]] },
      { view: "wheel", title: "Différentiel VAQ", text: "Un différentiel avant à commande électro-hydraulique bloque jusqu'à 100 % du couple sur la roue extérieure : la traction avant sort du virage comme une propulsion.", facts: [["Jantes", "18 pouces"], ["Freins", "340 mm"]] },
      { view: "rear", title: "EA888", text: "Le deux litres turbo de la famille EA888, 230 ch en Performance, un couple plat de 1 500 à 4 600 tr/min. La boîte DSG passe les rapports en 8 ms.", facts: [["Régime maxi", "6 500 tr/min"], ["Consommation", "6,4 l/100 km"]] },
      { view: "top", title: "Habitacle", text: "Le tissu à carreaux Clark, le pommeau en balle de golf, l'ergonomie sans faute. Une voiture de tous les jours qui reste une GTI.", facts: [["Coffre", "380 l"], ["Places", "5"]] },
    ],
    drive: { vmax: 250, accel: 9, brake: 11.5, grip: 1.05, mass: 1364, redline: 6500 },
  },
  {
    id: "gryaris",
    rank: 4,
    brand: "Toyota",
    model: "GR Yaris",
    tier: "Citadine de rallye",
    years: "2020 –",
    origin: "Motomachi, Japon",
    price: "≈ 40 000 €",
    tagline: "Une voiture de rallye homologuée pour la route, construite à la main.",
    lead: "Toyota devait produire 25 000 exemplaires pour homologuer sa Yaris WRC. Résultat : un trois cylindres de 261 ch, quatre roues motrices, un toit en carbone et une carrosserie trois portes qui n'existe sur aucune autre Yaris.",
    paint: "#e9ebee",
    vehicle: { src: "assets/cars/real/gryaris.glb", kind: "sketchfab", forward: "-z", length: 3.99, paintMaterial: "Intbodyunrefunblendbodyunrefunblend1Mtl" },
    credit: { title: "2020 Toyota GR Yaris", author: "DisneyCars", url: "https://sketchfab.com/3d-models/2020-toyota-gr-yaris-44cb958908b94aa5aad0d856994f35a3", license: "CC Attribution" },
    specs: { moteur: "3 cyl. 1,6 l turbo", puissance: "261 ch", couple: "360 Nm", zeroCent: "5,5 s", vmax: "230 km/h", poids: "1 280 kg", transmission: "Intégrale GR-Four, manuelle 6" },
    sections: [
      { view: "aero", title: "Homologation", text: "Toit abaissé de 91 mm, carrosserie élargie, trois portes : la GR Yaris ne partage avec la Yaris de série que les phares et les rétroviseurs. Chaque exemplaire est assemblé à la main sur la ligne GR de Motomachi.", facts: [["Toit", "carbone"], ["Longueur", "3,99 m"]] },
      { view: "wheel", title: "GR-Four", text: "La transmission intégrale répartit le couple 60/40, 50/50 ou 30/70 selon le mode. Sur route mouillée, c'est une des voitures les plus sûres et les plus rapides de son prix.", facts: [["Jantes", "18 pouces"], ["Freins", "356 mm"]] },
      { view: "rear", title: "Trois cylindres", text: "Le G16E-GTS est le trois cylindres de série le plus puissant du monde : 261 ch et 360 Nm pour 1,6 litre, avec un bloc à injection double et un turbo à roulement à billes.", facts: [["Régime maxi", "7 000 tr/min"], ["Puissance spécifique", "163 ch/l"]] },
      { view: "top", title: "Habitacle", text: "Sièges baquets, boîte manuelle courte, pas de mode automatique : la GR Yaris se conduit. Le bouton du différentiel central est la seule concession électronique.", facts: [["Places", "4"], ["Boîte", "manuelle"]] },
    ],
    drive: { vmax: 230, accel: 10, brake: 12, grip: 1.15, mass: 1280, redline: 7000 },
  },
  {
    id: "508",
    rank: 5,
    brand: "Peugeot",
    model: "508",
    tier: "Familiale",
    years: "2018 –",
    origin: "Mulhouse, France",
    price: "≈ 42 000 €",
    tagline: "La berline française qui a osé la ligne d'un coupé.",
    lead: "Cinq portes sans encadrement de vitres, une ligne de toit basse, un i-Cockpit qui place le compteur au-dessus du volant. La 508 assume d'être belle avant d'être pratique.",
    paint: "#5a6068",
    vehicle: { src: "assets/cars/real/508.glb", kind: "sketchfab", forward: "+z", length: 4.75 },
    credit: { title: "Peugeot 508", author: "Mona x Supercars", url: "https://sketchfab.com/3d-models/peugeot-508-8192f18de3d2431197c9e707666212c7", license: "CC Attribution" },
    specs: { moteur: "4 cyl. 1,6 l hybride rechargeable", puissance: "225 ch", couple: "360 Nm", zeroCent: "7,9 s", vmax: "240 km/h", poids: "1 780 kg", transmission: "Traction, auto 8" },
    sections: [
      { view: "aero", title: "Face avant", text: "Les crocs lumineux verticaux qui descendent dans le bouclier, la calandre à damier : la 508 a lancé le langage visuel de toute la gamme Peugeot actuelle.", facts: [["Hauteur", "1,40 m"], ["Longueur", "4,75 m"]] },
      { view: "wheel", title: "Tenue de route", text: "Suspension pilotée sur les versions GT, direction courte : c'est une berline qui se conduit comme une compacte, une tradition Peugeot depuis la 405.", facts: [["Jantes", "18 pouces"], ["Empattement", "2,79 m"]] },
      { view: "rear", title: "Hybride rechargeable", text: "Jusqu'à 50 km en tout électrique, puis le quatre cylindres PureTech reprend la main. Le meilleur des deux mondes pour un usage mixte.", facts: [["Autonomie électrique", "50 km"], ["Batterie", "11,5 kWh"]] },
      { view: "top", title: "Habitacle", text: "Volant compact, compteurs numériques en hauteur, touches piano en aluminium. On regarde la route sans baisser les yeux.", facts: [["Écran", "10 pouces"], ["Coffre", "487 l"]] },
    ],
    drive: { vmax: 240, accel: 8.5, brake: 11, grip: 0.95, mass: 1780, redline: 6200 },
  },
  {
    id: "tiguan",
    rank: 6,
    brand: "Volkswagen",
    model: "Tiguan",
    tier: "SUV familial",
    years: "2024 –",
    origin: "Wolfsburg, Allemagne",
    price: "≈ 45 000 €",
    tagline: "Le SUV le plus vendu d'Europe, troisième génération.",
    lead: "Rien d'ostentatoire, tout d'efficace. Le Tiguan est la définition allemande du SUV compact : un coffre immense, une qualité de fabrication irréprochable, une conduite sans surprise.",
    paint: "#e9ebee",
    vehicle: { src: "assets/cars/real/tiguan.glb", kind: "sketchfab", forward: "+z", length: 4.54 },
    credit: { title: "2024 Volkswagen Tiguan L Pro 380TSI 4WD R-line", author: "Ddiaz Design", url: "https://sketchfab.com/3d-models/2024-volkswagen-tiguan-l-pro-380tsi-4wd-r-line-0703b26f5c6446dabf1ab3caecce586f", license: "CC Attribution-NonCommercial-ShareAlike" },
    specs: { moteur: "4 cyl. 2,0 l TDI", puissance: "193 ch", couple: "400 Nm", zeroCent: "7,7 s", vmax: "220 km/h", poids: "1 750 kg", transmission: "4Motion, DSG 7" },
    sections: [
      { view: "aero", title: "Ligne", text: "Une bande lumineuse continue à l'avant, des flancs lisses, un Cx de 0,28 remarquable pour un SUV : le Tiguan est dessiné dans la soufflerie autant qu'au crayon.", facts: [["Cx", "0,28"], ["Longueur", "4,54 m"]] },
      { view: "wheel", title: "Quatre roues motrices", text: "La transmission 4Motion envoie le couple à l'arrière dès que l'avant patine. Sur neige ou route mouillée, c'est la différence.", facts: [["Jantes", "19 pouces"], ["Garde au sol", "190 mm"]] },
      { view: "rear", title: "Diesel moderne", text: "Le 2,0 TDI à double injection d'urée est parmi les plus propres de sa catégorie. 1 000 km d'autonomie par plein pour les longs trajets.", facts: [["Consommation", "5,6 l/100 km"], ["Réservoir", "55 l"]] },
      { view: "top", title: "Habitacle", text: "Écran de 15 pouces, molette de conduite rétroéclairée, sièges massants ergoActive. Le confort d'un segment supérieur.", facts: [["Coffre", "652 l"], ["Écran", "15 pouces"]] },
    ],
    drive: { vmax: 220, accel: 8, brake: 10.5, grip: 1.0, mass: 1750, redline: 4800 },
  },
  {
    id: "model3",
    rank: 7,
    brand: "Tesla",
    model: "Model 3",
    tier: "Berline électrique",
    years: "2017 –",
    origin: "Fremont, États-Unis",
    price: "≈ 45 000 €",
    tagline: "La voiture qui a rendu l'électrique désirable.",
    lead: "Pas de calandre, pas de bouton, un écran de 15 pouces et une accélération de sportive. La Model 3 est la voiture électrique la plus vendue de l'histoire, et celle qui a forcé tous les autres constructeurs à suivre.",
    paint: "#e6e8eb",
    vehicle: { src: "assets/cars/real/model3.glb", kind: "sketchfab", forward: "-z", length: 4.69, paintMaterial: "primary" },
    credit: { title: "Tesla 2018 Model 3", author: "Ameer Studio", url: "https://sketchfab.com/3d-models/tesla-2018-model-3-5ef9b845aaf44203b6d04e2c677e444f", license: "CC Attribution" },
    specs: { moteur: "2 moteurs électriques", puissance: "462 ch", couple: "660 Nm", zeroCent: "3,3 s", vmax: "261 km/h", poids: "1 847 kg", transmission: "Intégrale, réducteur fixe" },
    sections: [
      { view: "aero", title: "Sans calandre", text: "Un moteur électrique n'a pas besoin d'air : le nez est lisse, le Cx tombe à 0,23, le plus bas de sa catégorie. Les poignées de porte affleurent, les jantes sont carénées.", facts: [["Cx", "0,23"], ["Longueur", "4,69 m"]] },
      { view: "wheel", title: "Batterie au plancher", text: "Les 75 kWh sont sous le plancher : centre de gravité au niveau des essieux, répartition 50/50, rigidité de caisse d'une berline de luxe.", facts: [["Batterie", "75 kWh"], ["Autonomie", "547 km WLTP"]] },
      { view: "rear", title: "Deux moteurs", text: "Un moteur à induction à l'avant, un à aimants permanents à l'arrière. Version Performance : 462 ch et 3,3 s de 0 à 100 km/h, sans un bruit.", facts: [["Recharge", "250 kW"], ["Consommation", "16 kWh/100 km"]] },
      { view: "top", title: "Habitacle", text: "Un écran horizontal de 15 pouces et rien d'autre : vitesse, navigation, ventilation, tout passe par lui. Le toit est entièrement vitré.", facts: [["Coffres", "561 l"], ["Écran", "15 pouces"]] },
    ],
    drive: { vmax: 261, accel: 14, brake: 12, grip: 1.1, mass: 1847, redline: 16000 },
  },
  {
    id: "rs3",
    rank: 8,
    brand: "Audi",
    model: "RS 3",
    tier: "Compacte sportive",
    years: "2021 –",
    origin: "Ingolstadt, Allemagne",
    price: "≈ 70 000 €",
    tagline: "Le dernier cinq cylindres au monde, dans une compacte.",
    lead: "Un moteur qui n'existe nulle part ailleurs, un différentiel arrière qui répartit le couple roue par roue, et un mode dérapage homologué. La RS 3 est une anomalie assumée.",
    paint: "#2a63c9",
    vehicle: { src: "assets/cars/real/rs3.glb", kind: "sketchfab", forward: "-z", length: 4.39, paintMaterial: "MAT_RS3_2018_Base.004" },
    credit: { title: "2018 Audi RS 3 Sportback", author: "Galaxy Car Showroom", url: "https://sketchfab.com/3d-models/2018-audi-rs-3-sportback-77d3dcacacb7413e9685a27f77f651f8", license: "CC Attribution" },
    specs: { moteur: "5 cyl. 2,5 l TFSI", puissance: "400 ch", couple: "500 Nm", zeroCent: "3,8 s", vmax: "290 km/h", poids: "1 570 kg", transmission: "quattro, S tronic 7" },
    sections: [
      { view: "aero", title: "Face RS", text: "Calandre en nid d'abeilles plus large que celle de l'A3, prises d'air fonctionnelles pour les freins, becquet. Tout ce qui est noir est utile.", facts: [["Voie avant", "+33 mm"], ["Longueur", "4,39 m"]] },
      { view: "wheel", title: "Torque Splitter", text: "Deux embrayages multidisques à l'arrière répartissent le couple entre roue gauche et droite. En courbe, la roue extérieure pousse : la voiture pivote au lieu de sous-virer.", facts: [["Jantes", "19 pouces"], ["Freins", "375 mm"]] },
      { view: "rear", title: "Cinq cylindres", text: "L'ordre d'allumage 1-2-4-5-3 donne ce son inimitable, hérité des Audi Quattro de rallye des années 80. 400 ch depuis 2,5 litres.", facts: [["Régime maxi", "7 000 tr/min"], ["Son", "1-2-4-5-3"]] },
      { view: "top", title: "Habitacle", text: "Compteurs RS avec compte-tours à barres, sièges baquets, volant à méplat. Un mode RS Torque Rear pour le dérapage contrôlé, sur circuit.", facts: [["Coffre", "282 l"], ["Modes", "7"]] },
    ],
    drive: { vmax: 290, accel: 13, brake: 13, grip: 1.15, mass: 1570, redline: 7000 },
  },
  {
    id: "911",
    rank: 9,
    brand: "Porsche",
    model: "911 Carrera 4S",
    tier: "Sportive",
    years: "2019 –",
    origin: "Zuffenhausen, Allemagne",
    price: "≈ 150 000 €",
    tagline: "Soixante ans de la même idée, jamais la même voiture.",
    lead: "Le moteur à l'arrière, la silhouette qu'un enfant dessine, et une évolution continue depuis 1963. La 992 Carrera 4S ajoute quatre roues motrices et un six cylindres à plat biturbo de 450 ch à une recette inchangée.",
    paint: "#f2c81e",
    vehicle: { src: "assets/cars/real/911.glb", kind: "sketchfab", forward: "+z", length: 4.52, paintMaterial: "car_vpnt_911992Carrera4S" },
    credit: { title: "2019 Porsche 911 Carrera 4S (992)", author: "Ddiaz Design", url: "https://sketchfab.com/3d-models/4e324fdfada24355aba3f34cf09a9552", license: "CC Attribution-NonCommercial-ShareAlike" },
    specs: { moteur: "6 cyl. à plat 3,0 l biturbo", puissance: "450 ch", couple: "530 Nm", zeroCent: "3,6 s", vmax: "306 km/h", poids: "1 565 kg", transmission: "Intégrale, PDK 8" },
    sections: [
      { view: "aero", title: "Silhouette", text: "Le pare-brise est plus vertical, les ailes bombées, la ligne de toit tombe jusqu'au pare-chocs. La 911 est la seule voiture qu'on reconnaît de n'importe quel angle.", facts: [["Cx", "0,29"], ["Longueur", "4,52 m"]] },
      { view: "wheel", title: "Moteur arrière", text: "Le poids sur les roues arrière donne une motricité en sortie de virage qu'aucune voiture à moteur avant n'égale ; la transmission intégrale de la 4S envoie le surplus à l'avant. L'art de Porsche est de dompter ce que cela implique au freinage.", facts: [["Jantes", "20 / 21 pouces"], ["Répartition", "39 / 61"]] },
      { view: "rear", title: "Biturbo", text: "Deux turbos symétriques sur un six cylindres à plat de trois litres : 450 ch, 530 Nm disponibles de 2 300 à 5 000 tr/min. Le son reste celui d'un flat-six, l'élasticité est celle d'un V8.", facts: [["Régime maxi", "7 500 tr/min"], ["0 – 200 km/h", "12,4 s"]] },
      { view: "top", title: "Habitacle", text: "Compte-tours analogique au centre, écrans de part et d'autre, bouton de démarrage à gauche comme aux 24 Heures du Mans, matériaux sans faute. Deux places, deux petits sièges à l'arrière.", facts: [["Coffre avant", "132 l"], ["Places", "2 + 2"]] },
    ],
    drive: { vmax: 306, accel: 14.5, brake: 14.5, grip: 1.25, mass: 1565, redline: 7500 },
  },
  {
    id: "x5m",
    rank: 10,
    brand: "BMW",
    model: "X5 M Competition",
    tier: "SUV de performance",
    years: "2023 –",
    origin: "Spartanburg, États-Unis",
    price: "≈ 165 000 €",
    tagline: "Deux tonnes trois, et le temps d'une supercar au sprint.",
    lead: "Un V8 biturbo de 625 ch dans un SUV de sept places possibles. Le X5 M est une contradiction que BMW a résolue à coups de suspension active et de différentiels pilotés.",
    paint: "#eef0f2",
    vehicle: { src: "assets/cars/real/x5m.glb", kind: "sketchfab", forward: "+z", length: 4.94, paintMaterial: "edge_color141164193255" },
    credit: { title: "2020 BMW X5 M Competition", author: "David_Holiday", url: "https://sketchfab.com/3d-models/2020-bmw-x5-m-competition-9b211d525797457e988c903f67d0b753", license: "CC Attribution" },
    specs: { moteur: "V8 4,4 l biturbo hybride léger", puissance: "625 ch", couple: "750 Nm", zeroCent: "3,9 s", vmax: "290 km/h", poids: "2 385 kg", transmission: "M xDrive, auto 8" },
    sections: [
      { view: "aero", title: "Présence", text: "Les haricots éclairés, les ailes élargies, les quatre sorties d'échappement : rien n'est discret, et c'est le but. Le X5 M occupe la route.", facts: [["Largeur", "2,02 m"], ["Longueur", "4,94 m"]] },
      { view: "wheel", title: "Châssis actif", text: "Barres antiroulis actives, amortisseurs pilotés, différentiel arrière M. Les 2 385 kg se font oublier en courbe, ce qui ne devrait pas être possible.", facts: [["Jantes", "21 / 22 pouces"], ["Freins", "395 mm"]] },
      { view: "rear", title: "V8 S68", text: "Le même V8 que la M5, avec un alterno-démarreur de 48 V qui gomme le turbo lag. 750 Nm disponibles dès 1 800 tr/min.", facts: [["Régime maxi", "7 200 tr/min"], ["Consommation", "12,5 l/100 km"]] },
      { view: "top", title: "Habitacle", text: "Cuir Merino étendu, écran incurvé, sièges M multifonctions chauffants et ventilés. Une pièce à vivre qui accélère.", facts: [["Coffre", "650 l"], ["Écran", "14,9 pouces"]] },
    ],
    drive: { vmax: 290, accel: 12, brake: 12.5, grip: 1.05, mass: 2385, redline: 7200 },
  },
  {
    id: "g63",
    rank: 11,
    brand: "Mercedes-AMG",
    model: "G 63",
    tier: "Tout-terrain de luxe",
    years: "2018 –",
    origin: "Graz, Autriche",
    price: "≈ 210 000 €",
    tagline: "Un engin militaire de 1979 devenu l'objet le plus désiré de Los Angeles.",
    lead: "Le Classe G a été dessiné pour l'armée. Quarante ans plus tard, AMG y loge un V8 biturbo de 585 ch et le vend à des stars. La silhouette, les charnières apparentes et le bruit des serrures n'ont pas changé.",
    paint: "#d9141c",
    vehicle: { src: "assets/cars/real/g63.glb", kind: "sketchfab", forward: "+z", length: 4.87, paintMaterial: "bodypaint" },
    credit: { title: "Mersedes-Benz G63 AMG", author: "Black Snow", url: "https://sketchfab.com/3d-models/mersedes-benz-g63-amg-e5e2a1d2238048a1a494b3df983c16bb", license: "CC Attribution" },
    specs: { moteur: "V8 4,0 l biturbo", puissance: "585 ch", couple: "850 Nm", zeroCent: "4,5 s", vmax: "240 km/h", poids: "2 560 kg", transmission: "Intégrale, auto 9" },
    sections: [
      { view: "aero", title: "Le carré", text: "Le Cx de 0,53 est celui d'une armoire, et c'est voulu : les pare-chocs, les charnières, les clignotants sur le capot sont ceux de 1979. Le G est la seule voiture qui a réussi à ne pas changer.", facts: [["Cx", "0,53"], ["Hauteur", "1,97 m"]] },
      { view: "wheel", title: "Trois blocages", text: "Trois différentiels blocables à 100 %, une boîte de transfert à gamme courte, 24 cm de garde au sol. Le G 63 passe partout où sa largeur le permet.", facts: [["Garde au sol", "241 mm"], ["Gué", "70 cm"]] },
      { view: "rear", title: "V8 AMG", text: "Le M177, V8 4 litres biturbo assemblé à la main à Affalterbach, sortant par deux paires d'échappements latéraux avant les roues arrière. Le son est une signature.", facts: [["Régime maxi", "7 000 tr/min"], ["Consommation", "14,4 l/100 km"]] },
      { view: "top", title: "Habitacle", text: "Deux écrans de 12,3 pouces dans une planche de bord verticale, une poignée de maintien devant le passager, des sièges massants. Le luxe dans une carrosserie de camion.", facts: [["Coffre", "667 l"], ["Places", "5"]] },
    ],
    drive: { vmax: 240, accel: 11, brake: 11, grip: 1.0, mass: 2560, redline: 7000 },
  },
  {
    id: "db11",
    rank: 12,
    brand: "Aston Martin",
    model: "DB11",
    tier: "Grand tourisme",
    years: "2016 –",
    origin: "Gaydon, Angleterre",
    price: "≈ 230 000 €",
    tagline: "Le premier V12 biturbo d'Aston Martin, et le plus beau capot du siècle.",
    lead: "La DB11 a rouvert le livre des DB après la DB9. Un V12 de 5,2 litres, une carrosserie en aluminium collé, une aérodynamique invisible : les prises d'air dans les montants de portes remplacent tout aileron.",
    paint: "#375d89",
    vehicle: { src: "assets/cars/real/db11.glb", kind: "sketchfab", forward: "-z", length: 4.74, paintMaterial: "Body_Color" },
    credit: { title: "2017 Aston Martin DB11 [5.2L Twin-Turbo V12]", author: "Hari Prasath R", url: "https://sketchfab.com/3d-models/2017-aston-martin-db11-52l-twin-turbo-v12-936854ba7dde46f09a47d355d433808c", license: "CC Attribution" },
    specs: { moteur: "V12 5,2 l biturbo", puissance: "639 ch", couple: "700 Nm", zeroCent: "3,7 s", vmax: "334 km/h", poids: "1 875 kg", transmission: "Propulsion, auto 8" },
    sections: [
      { view: "aero", title: "Aeroblade", text: "L'air entre dans des prises à la base des montants arrière, traverse la carrosserie et ressort par une fente au bout du coffre : un aileron virtuel, invisible, qui plaque l'arrière sans rien ajouter au dessin.", facts: [["Cx", "0,35"], ["Longueur", "4,74 m"]] },
      { view: "wheel", title: "Châssis collé", text: "Structure en aluminium extrudé et collé, suspension adaptative Skyhook, différentiel arrière à commande électronique. Une GT de 1 875 kg qui tourne comme une sportive.", facts: [["Jantes", "20 pouces"], ["Freins", "400 mm"]] },
      { view: "rear", title: "V12 AE31", text: "Le premier moteur d'Aston Martin conçu pour le turbo : 5,2 litres, deux turbos, désactivation de six cylindres en croisière. 639 ch dans la version AMR.", facts: [["Régime maxi", "7 000 tr/min"], ["Cylindres", "12"]] },
      { view: "top", title: "Habitacle", text: "Cuir Bridge of Weir, bois, aluminium brossé et un système multimédia emprunté à Mercedes. Deux places à l'arrière, pour des enfants ou des sacs.", facts: [["Coffre", "270 l"], ["Places", "2 + 2"]] },
    ],
    drive: { vmax: 334, accel: 14, brake: 14, grip: 1.2, mass: 1875, redline: 7000 },
  },
  {
    id: "458",
    rank: 13,
    brand: "Ferrari",
    model: "458 Spider",
    tier: "Supercar",
    years: "2011 – 2015",
    origin: "Maranello, Italie",
    price: "≈ 260 000 €",
    tagline: "Le dernier V8 atmosphérique de Maranello, à ciel ouvert.",
    lead: "570 ch sans turbo, 9 000 tr/min, un toit rigide en aluminium qui se replie en 14 secondes. La 458 est la Ferrari que les collectionneurs désignent comme la fin d'une époque.",
    paint: "#f1c40f",
    vehicle: { src: "assets/cars/real/458.glb", kind: "sketchfab", forward: "+z", length: 4.53, paintMaterial: "Fphong7SG1" },
    credit: { title: "2013 Ferrari 458 Spider", author: "Ddiaz Design", url: "https://sketchfab.com/3d-models/2013-ferrari-458-spider-d12eab5e5c6d421da468e1c348a860a6", license: "CC Attribution" },
    specs: { moteur: "V8 4,5 l atmosphérique", puissance: "570 ch", couple: "540 Nm", zeroCent: "3,4 s", vmax: "320 km/h", poids: "1 430 kg", transmission: "Propulsion, F1 7" },
    sections: [
      { view: "aero", title: "Aérodynamique", text: "Les deux ailettes sous la calandre se déforment à haute vitesse pour réduire la portance, sans commande électronique. Le fond plat et le diffuseur produisent 360 kg d'appui à 200 km/h.", facts: [["Appui à 200 km/h", "360 kg"], ["Cx", "0,33"]] },
      { view: "wheel", title: "Châssis et freinage", text: "Structure en aluminium, jantes de 20 pouces, disques carbone-céramique Brembo de 398 mm à l'avant. E-Diff et F1-Trac pilotés par le même calculateur.", facts: [["Freins avant", "398 mm"], ["Jantes", "20 pouces"]] },
      { view: "rear", title: "Moteur", text: "V8 de 4,5 litres à injection directe, position centrale arrière. 570 ch à 9 000 tr/min : la plus haute puissance spécifique jamais obtenue sur un atmosphérique de série.", facts: [["Régime maxi", "9 000 tr/min"], ["Puissance spécifique", "127 ch/l"]] },
      { view: "top", title: "Habitacle", text: "Toutes les commandes sont sur le volant : clignotants, essuie-glaces, phares, Manettino. Aucun levier derrière le volant hormis les palettes.", facts: [["Toit", "14 s"], ["Places", "2"]] },
    ],
    drive: { vmax: 320, accel: 15, brake: 15, grip: 1.3, mass: 1430, redline: 9000 },
  },
  {
    id: "revuelto",
    rank: 14,
    brand: "Lamborghini",
    model: "Revuelto",
    tier: "Supercar hybride",
    years: "2023 –",
    origin: "Sant'Agata Bolognese, Italie",
    price: "≈ 500 000 €",
    tagline: "Un V12, trois moteurs électriques, 1 015 chevaux.",
    lead: "Lamborghini a refusé d'abandonner le V12 atmosphérique. La Revuelto l'entoure de trois moteurs électriques et d'une coque monobloc en carbone. Le résultat est la voiture de série la plus rapide jamais produite par la marque.",
    paint: "#e8641c",
    vehicle: { src: "assets/cars/real/revuelto.glb", kind: "sketchfab", forward: "+z", length: 4.95 },
    credit: { title: "Free Lamborghini Revuelto", author: "ALIEEEN", url: "https://sketchfab.com/3d-models/free-lamborghini-revuelto-cf52245eb68f48daa909c7ad2a8deaa3", license: "CC Attribution" },
    specs: { moteur: "V12 6,5 l atmosphérique + 3 électriques", puissance: "1 015 ch", couple: "725 Nm (V12)", zeroCent: "2,5 s", vmax: "350 km/h", poids: "1 772 kg", transmission: "Intégrale, DCT 8" },
    sections: [
      { view: "aero", title: "Forme en Y", text: "Chaque prise d'air, chaque phare, chaque sortie d'échappement dessine un Y. Le capot avant abrite le moteur électrique et un coffre ; la voiture est sculptée par l'air qui la traverse.", facts: [["Appui", "+66 % vs Aventador"], ["Longueur", "4,95 m"]] },
      { view: "wheel", title: "Quatre roues motrices électriques", text: "Deux moteurs à l'avant, un par roue, capables de vectoriser le couple et de faire reculer la voiture sans le V12. Le train arrière reste mécanique.", facts: [["Jantes", "21 / 22 pouces"], ["Freins", "410 mm carbone"]] },
      { view: "rear", title: "V12 L545", text: "Le moteur est tourné de 180° par rapport à l'Aventador, la boîte est derrière lui, transversale. 825 ch pour le seul V12, à 9 250 tr/min.", facts: [["Régime maxi", "9 500 tr/min"], ["Poids moteur", "218 kg"]] },
      { view: "top", title: "Habitacle", text: "Trois écrans, un volant qui regroupe les modes de conduite sur deux molettes, des sièges en carbone. Treize combinaisons de conduite, dont un mode électrique pur.", facts: [["Modes", "13"], ["Autonomie électrique", "10 km"]] },
    ],
    drive: { vmax: 350, accel: 22, brake: 17, grip: 1.45, mass: 1772, redline: 9500 },
  },
  {
    id: "phantom",
    rank: 15,
    brand: "Rolls-Royce",
    model: "Phantom",
    tier: "Limousine",
    years: "2017 –",
    origin: "Goodwood, Angleterre",
    price: "≈ 500 000 €",
    tagline: "La voiture la plus silencieuse du monde. Rien d'autre à prouver.",
    lead: "130 kg d'isolant, des pneus remplis de mousse, une suspension qui lit la route avec une caméra. La Phantom VIII n'a pas de compte-tours : elle a une jauge de « puissance en réserve », toujours proche de 100 %.",
    paint: "#151619",
    vehicle: { src: "assets/cars/real/phantom.glb", kind: "sketchfab", forward: "+z", length: 5.76, paintMaterial: "car_body_in" },
    credit: { title: "rollsroyce phantom", author: "Jaggu_wrld", url: "https://sketchfab.com/3d-models/rollsroyce-phantom-1a2f117c8f1b4324b5a5dd70d38d396b", license: "CC Attribution" },
    specs: { moteur: "V12 6,75 l biturbo", puissance: "571 ch", couple: "900 Nm", zeroCent: "5,3 s", vmax: "250 km/h", poids: "2 560 kg", transmission: "Propulsion, auto 8" },
    sections: [
      { view: "aero", title: "Le Panthéon", text: "La calandre est celle d'un temple grec, l'Esprit d'Extase se rétracte dans le capot, les portes s'ouvrent à l'envers et se ferment seules. Rien n'est là pour l'aérodynamique ; tout est là pour l'effet.", facts: [["Longueur", "5,76 m"], ["Portes", "antagonistes"]] },
      { view: "wheel", title: "Tapis volant", text: "La suspension pneumatique est pilotée par une caméra qui lit la route dix mètres devant. Les pneus contiennent de la mousse pour absorber leur propre bruit.", facts: [["Jantes", "22 pouces"], ["Isolant", "130 kg"]] },
      { view: "rear", title: "V12 6,75 litres", text: "Le V12 biturbo produit 900 Nm dès 1 700 tr/min : la Phantom n'accélère pas, elle se déplace. Le moteur est inaudible à 100 km/h.", facts: [["Couple", "900 Nm à 1 700 tr/min"], ["Cylindres", "12"]] },
      { view: "top", title: "Habitacle", text: "La Galerie : une vitre d'un seul tenant sur toute la planche de bord, derrière laquelle chaque client commande une œuvre d'art. Le ciel de toit est un ciel étoilé de fibres optiques.", facts: [["Étoiles", "1 340 fibres"], ["Places", "5"]] },
    ],
    drive: { vmax: 250, accel: 8.5, brake: 10, grip: 0.95, mass: 2560, redline: 6000 },
  },
  {
    id: "jesko",
    rank: 16,
    brand: "Koenigsegg",
    model: "Jesko",
    tier: "Hypercar",
    years: "2021 –",
    origin: "Ängelholm, Suède",
    price: "≈ 3 000 000 €",
    tagline: "1 600 chevaux, une boîte à neuf rapports qui n'existe nulle part ailleurs.",
    lead: "Christian von Koenigsegg a nommé cette voiture d'après son père. V8 de 5 litres poussé à 1 600 ch au bioéthanol, boîte Light Speed à sept embrayages qui passe directement du 9e au 4e, et un aileron qui produit 1 400 kg d'appui.",
    paint: "#e8e9ec",
    vehicle: { src: "assets/cars/real/jesko.glb", kind: "sketchfab", forward: "+z", length: 4.61, paintMaterial: "jeskoVehicle_Exterior_mm_ext1" },
    credit: { title: "2020 Koenigsegg Jesko", author: "Ddiaz Design", url: "https://sketchfab.com/3d-models/2020-koenigsegg-jesko-c657f51fb0db43e38fea172dfa385287", license: "CC Attribution" },
    specs: { moteur: "V8 5,0 l biturbo", puissance: "1 600 ch (E85)", couple: "1 500 Nm", zeroCent: "2,5 s", vmax: "> 480 km/h (Absolut)", poids: "1 420 kg", transmission: "Propulsion, LST 9" },
    sections: [
      { view: "aero", title: "1 400 kg d'appui", text: "L'aileron arrière à double montant, le splitter, les canaux sous la caisse : à 250 km/h, la Jesko Attack pèse virtuellement deux fois son poids sur ses pneus. La version Absolut, elle, retire tout pour dépasser 480 km/h.", facts: [["Appui", "1 400 kg"], ["Longueur", "4,61 m"]] },
      { view: "wheel", title: "Triplex", text: "Un troisième amortisseur horizontal relie les deux suspensions arrière pour empêcher l'arrière de s'écraser à l'accélération. Les jantes en carbone creux pèsent 6 kg.", facts: [["Jantes", "carbone, 20 / 21 pouces"], ["Freins", "410 mm carbone"]] },
      { view: "rear", title: "V8 à vilebrequin plat", text: "Le vilebrequin pèse 12,5 kg, les turbos sont alimentés par un réservoir d'air comprimé pour supprimer le temps de réponse. 1 280 ch à l'essence, 1 600 ch à l'E85.", facts: [["Régime maxi", "8 500 tr/min"], ["Rapports", "9"]] },
      { view: "top", title: "Habitacle", text: "Le volant porte deux petits écrans qui tournent avec lui ; l'instrumentation reste lisible en virage. Les portes s'ouvrent en ciseaux vers l'avant, la marque de fabrique de Koenigsegg.", facts: [["Places", "2"], ["Exemplaires", "125"]] },
    ],
    drive: { vmax: 480, accel: 26, brake: 18, grip: 1.5, mass: 1420, redline: 8500 },
  },
  {
    id: "chiron",
    rank: 17,
    brand: "Bugatti",
    model: "Chiron Super Sport",
    tier: "Hypercar",
    years: "2021 – 2024",
    origin: "Molsheim, France",
    price: "≈ 3 800 000 €",
    tagline: "Seize cylindres, quatre turbos, 440 km/h. Le sommet.",
    lead: "La Chiron Super Sport est la voiture de série qui a franchi 490 km/h en essais. Chaque exemplaire est assemblé à la main à Molsheim, en Alsace, en six mois. Il y en a eu moins de cent.",
    paint: "#15171c",
    vehicle: { src: "assets/cars/real/chiron.glb", kind: "sketchfab", forward: "+z", length: 4.79 },
    credit: { title: "Bugatti Chiron Super Sport 300+", author: "kevin (ケビン)", url: "https://sketchfab.com/3d-models/bugatti-chiron-super-sport-300-24c595760e194e63bcfc96508338fd3a", license: "CC Attribution" },
    specs: { moteur: "W16 8,0 l quadri-turbo", puissance: "1 600 ch", couple: "1 600 Nm", zeroCent: "2,4 s", vmax: "440 km/h", poids: "1 995 kg", transmission: "Intégrale, DSG 7" },
    sections: [
      { view: "aero", title: "Longue queue", text: "L'arrière est allongé de 25 cm par rapport à la Chiron pour retarder le décollement de l'air. À 440 km/h, la voiture traverse 122 mètres d'air chaque seconde.", facts: [["Longueur", "4,79 m"], ["Cx", "0,35"]] },
      { view: "wheel", title: "Pneus", text: "Michelin a développé des pneus spécifiques, contrôlés aux rayons X avant montage. Au-delà de 400 km/h, chaque gramme de la bande de roulement subit 3 800 g.", facts: [["Jantes", "20 / 21 pouces"], ["Freins", "420 mm carbone"]] },
      { view: "rear", title: "W16", text: "Seize cylindres en W, huit litres, quatre turbocompresseurs qui s'enclenchent par paires. À plein régime, le moteur avale 60 000 litres d'air par minute.", facts: [["Régime maxi", "7 100 tr/min"], ["Radiateurs", "10"]] },
      { view: "top", title: "Habitacle", text: "Aluminium fraisé, cuir, aucun écran central : la vitesse est affichée sur un cadran mécanique gradué jusqu'à 500. Bugatti refuse les écrans qui vieillissent.", facts: [["Compteur", "500 km/h"], ["Places", "2"]] },
    ],
    drive: { vmax: 420, accel: 24, brake: 17, grip: 1.4, mass: 1995, redline: 7100 },
  },
];

export function carById(id) {
  return CARS.find((c) => c.id === id) || CARS.find((c) => c.id === "458");
}

export function carFromLocation() {
  const id = new URLSearchParams(location.search).get("car");
  return carById(id || (localStorage.getItem("car") || "458"));
}

export function rememberCar(id) {
  try {
    localStorage.setItem("car", id);
  } catch (e) {
    /* stockage indisponible : on ignore */
  }
}
