// La collection : dix voitures, de la plus accessible à la plus prestigieuse.
// Chaque entrée alimente le studio (textes, fiche, caméras) et la conduite (performances).
// Les modèles 3D sont des assets CC0 (Quaternius, Kenney) repeints aux couleurs de chaque marque ;
// les silhouettes sont stylisées, les chiffres sont ceux des voitures réelles.

const Q = "assets/cars/";
const K = "assets/cars/kenney/";

export const CARS = [
  {
    id: "sandero",
    rank: 1,
    brand: "Dacia",
    model: "Sandero",
    tier: "Accessible",
    years: "2021 –",
    origin: "Mioveni, Roumanie",
    price: "≈ 12 000 €",
    tagline: "La voiture neuve la moins chère d'Europe, et la plus vendue aux particuliers.",
    lead: "Un seul objectif : l'essentiel, bien fait. Moteur trois cylindres, boîte manuelle, un coffre de 328 litres et rien qui ne serve pas tous les jours.",
    paint: "#c9b79c",
    vehicle: { src: Q + "q-citadine.glb", kind: "quaternius", length: 4.09 },
    specs: { moteur: "3 cyl. 1,0 l turbo", puissance: "90 ch", couple: "160 Nm", zeroCent: "12,0 s", vmax: "175 km/h", poids: "1 050 kg", transmission: "Traction, manuelle 6" },
    sections: [
      { view: "aero", title: "Simplicité", text: "Pas de ligne décorative : les flancs sont plans, la calandre est peinte, les optiques LED sont le seul geste. Chaque pièce a un prix, chaque prix est compté.", facts: [["Coffre", "328 l"], ["Longueur", "4,09 m"]] },
      { view: "wheel", title: "Roues et suspension", text: "Jantes de 15 pouces en acier avec enjoliveurs, pneus à taille haute : le confort avant tout sur des routes qui ne sont pas toujours parfaites.", facts: [["Jantes", "15 pouces"], ["Garde au sol", "163 mm"]] },
      { view: "rear", title: "Moteur", text: "Le TCe 90, trois cylindres turbo partagé avec la Clio. Sobre, discret, et assez de couple bas pour ne pas avoir à rétrograder en ville.", facts: [["Consommation", "5,3 l/100 km"], ["CO₂", "120 g/km"]] },
      { view: "top", title: "Habitacle", text: "Un écran de 8 pouces qui reflète simplement le téléphone, des commandes physiques pour la clim, cinq vraies places. Rien à apprendre.", facts: [["Places", "5"], ["Écran", "8 pouces"]] },
    ],
    drive: { vmax: 175, accel: 5.5, brake: 9, grip: 0.85, mass: 1050 },
  },
  {
    id: "clio",
    rank: 2,
    brand: "Renault",
    model: "Clio",
    tier: "Citadine",
    years: "2019 –",
    origin: "Bursa, Turquie",
    price: "≈ 19 000 €",
    tagline: "Trente ans de best-seller français, cinquième génération.",
    lead: "La citadine qui a défini la catégorie en 1990. Aujourd'hui hybride E-Tech, avec une finition qui regarde une gamme au-dessus.",
    paint: "#e0521c",
    vehicle: { src: K + "hatchback-sports.glb", kind: "kenney", length: 4.05, width: 1.8 },
    specs: { moteur: "4 cyl. 1,6 l hybride E-Tech", puissance: "145 ch", couple: "205 Nm", zeroCent: "9,3 s", vmax: "180 km/h", poids: "1 300 kg", transmission: "Traction, multimode" },
    sections: [
      { view: "aero", title: "Dessin", text: "Le capot est nervuré, les optiques en C sont devenues la signature de la marque. Un dessin tendu qui vieillit bien.", facts: [["Cx", "0,32"], ["Longueur", "4,05 m"]] },
      { view: "wheel", title: "Châssis", text: "Plateforme CMF-B partagée avec la Sandero et le Captur, mais réglée plus ferme : la Clio reste la référence de la catégorie sur route sinueuse.", facts: [["Jantes", "17 pouces"], ["Empattement", "2,58 m"]] },
      { view: "rear", title: "Hybride", text: "Une boîte à crabots sans embrayage héritée de la Formule 1, deux moteurs électriques : en ville, 80 % du temps se fait moteur essence coupé.", facts: [["Consommation", "4,2 l/100 km"], ["Batterie", "1,2 kWh"]] },
      { view: "top", title: "Habitacle", text: "Écran vertical de 9,3 pouces, sellerie recyclée, planche de bord souple. La qualité perçue a fait un bond entre la quatrième et la cinquième génération.", facts: [["Écran", "9,3 pouces"], ["Coffre", "301 l"]] },
    ],
    drive: { vmax: 180, accel: 7, brake: 10, grip: 0.9, mass: 1300 },
  },
  {
    id: "508",
    rank: 3,
    brand: "Peugeot",
    model: "508",
    tier: "Familiale",
    years: "2018 –",
    origin: "Mulhouse, France",
    price: "≈ 42 000 €",
    tagline: "La berline française qui a osé la ligne d'un coupé.",
    lead: "Cinq portes sans encadrement de vitres, une ligne de toit basse, un i-Cockpit qui place le compteur au-dessus du volant. La 508 assume d'être belle avant d'être pratique.",
    paint: "#1f3a6d",
    vehicle: { src: Q + "q-berline.glb", kind: "quaternius", length: 4.75 },
    specs: { moteur: "4 cyl. 1,6 l hybride rechargeable", puissance: "225 ch", couple: "360 Nm", zeroCent: "7,9 s", vmax: "240 km/h", poids: "1 780 kg", transmission: "Traction, auto 8" },
    sections: [
      { view: "aero", title: "Face avant", text: "Les crocs lumineux verticaux qui descendent dans le bouclier, la calandre à damier : la 508 a lancé le langage visuel de toute la gamme Peugeot actuelle.", facts: [["Hauteur", "1,40 m"], ["Longueur", "4,75 m"]] },
      { view: "wheel", title: "Tenue de route", text: "Suspension pilotée sur les versions GT, direction courte : c'est une berline qui se conduit comme une compacte, une tradition Peugeot depuis la 405.", facts: [["Jantes", "18 pouces"], ["Empattement", "2,79 m"]] },
      { view: "rear", title: "Hybride rechargeable", text: "Jusqu'à 50 km en tout électrique, puis le quatre cylindres PureTech reprend la main. Le meilleur des deux mondes pour un usage mixte.", facts: [["Autonomie électrique", "50 km"], ["Batterie", "11,5 kWh"]] },
      { view: "top", title: "Habitacle", text: "Volant compact, compteurs numériques en hauteur, touches piano en aluminium. On regarde la route sans baisser les yeux.", facts: [["Écran", "10 pouces"], ["Coffre", "487 l"]] },
    ],
    drive: { vmax: 240, accel: 8.5, brake: 11, grip: 0.95, mass: 1780 },
  },
  {
    id: "tiguan",
    rank: 4,
    brand: "Volkswagen",
    model: "Tiguan",
    tier: "SUV familial",
    years: "2024 –",
    origin: "Wolfsburg, Allemagne",
    price: "≈ 45 000 €",
    tagline: "Le SUV le plus vendu d'Europe, troisième génération.",
    lead: "Rien d'ostentatoire, tout d'efficace. Le Tiguan est la définition allemande du SUV compact : un coffre immense, une qualité de fabrication irréprochable, une conduite sans surprise.",
    paint: "#6b7078",
    vehicle: { src: Q + "q-suv.glb", kind: "quaternius", length: 4.54 },
    specs: { moteur: "4 cyl. 2,0 l TDI", puissance: "193 ch", couple: "400 Nm", zeroCent: "7,7 s", vmax: "220 km/h", poids: "1 750 kg", transmission: "4Motion, DSG 7" },
    sections: [
      { view: "aero", title: "Ligne", text: "Une bande lumineuse continue à l'avant, des flancs lisses, un Cx de 0,28 remarquable pour un SUV : le Tiguan est dessiné dans la soufflerie autant qu'au crayon.", facts: [["Cx", "0,28"], ["Longueur", "4,54 m"]] },
      { view: "wheel", title: "Quatre roues motrices", text: "La transmission 4Motion envoie le couple à l'arrière dès que l'avant patine. Sur neige ou route mouillée, c'est la différence.", facts: [["Jantes", "19 pouces"], ["Garde au sol", "190 mm"]] },
      { view: "rear", title: "Diesel moderne", text: "Le 2,0 TDI à double injection d'urée est parmi les plus propres de sa catégorie. 1 000 km d'autonomie par plein pour les longs trajets.", facts: [["Consommation", "5,6 l/100 km"], ["Réservoir", "55 l"]] },
      { view: "top", title: "Habitacle", text: "Écran de 15 pouces, molette de conduite rétroéclairée, sièges massants ergoActive. Le confort d'un segment supérieur.", facts: [["Coffre", "652 l"], ["Écran", "15 pouces"]] },
    ],
    drive: { vmax: 220, accel: 8, brake: 10.5, grip: 1.0, mass: 1750 },
  },
  {
    id: "rs3",
    rank: 5,
    brand: "Audi",
    model: "RS 3",
    tier: "Compacte sportive",
    years: "2021 –",
    origin: "Ingolstadt, Allemagne",
    price: "≈ 70 000 €",
    tagline: "Le dernier cinq cylindres au monde, dans une compacte.",
    lead: "Un moteur qui n'existe nulle part ailleurs, un différentiel arrière qui répartit le couple roue par roue, et un mode dérapage homologué. La RS 3 est une anomalie assumée.",
    paint: "#7c8087",
    vehicle: { src: K + "sedan-sports.glb", kind: "kenney", length: 4.39, width: 1.85 },
    specs: { moteur: "5 cyl. 2,5 l TFSI", puissance: "400 ch", couple: "500 Nm", zeroCent: "3,8 s", vmax: "290 km/h", poids: "1 570 kg", transmission: "quattro, S tronic 7" },
    sections: [
      { view: "aero", title: "Face RS", text: "Calandre en nid d'abeilles plus large que celle de l'A3, prises d'air fonctionnelles pour les freins, becquet. Tout ce qui est noir est utile.", facts: [["Voie avant", "+33 mm"], ["Longueur", "4,39 m"]] },
      { view: "wheel", title: "Torque Splitter", text: "Deux embrayages multidisques à l'arrière répartissent le couple entre roue gauche et droite. En courbe, la roue extérieure pousse : la voiture pivote au lieu de sous-virer.", facts: [["Jantes", "19 pouces"], ["Freins", "375 mm"]] },
      { view: "rear", title: "Cinq cylindres", text: "L'ordre d'allumage 1-2-4-5-3 donne ce son inimitable, hérité des Audi Quattro de rallye des années 80. 400 ch depuis 2,5 litres.", facts: [["Régime maxi", "7 000 tr/min"], ["Son", "1-2-4-5-3"]] },
      { view: "top", title: "Habitacle", text: "Compteurs RS avec compte-tours à barres, sièges baquets, volant à méplat. Un mode RS Torque Rear pour le dérapage contrôlé, sur circuit.", facts: [["Coffre", "282 l"], ["Modes", "7"]] },
    ],
    drive: { vmax: 290, accel: 13, brake: 13, grip: 1.15, mass: 1570 },
  },
  {
    id: "x5m",
    rank: 6,
    brand: "BMW",
    model: "X5 M Competition",
    tier: "SUV de performance",
    years: "2023 –",
    origin: "Spartanburg, États-Unis",
    price: "≈ 165 000 €",
    tagline: "Deux tonnes trois, et le temps d'une supercar au sprint.",
    lead: "Un V8 biturbo de 625 ch dans un SUV de sept places possibles. Le X5 M est une contradiction que BMW a résolue à coups de suspension active et de différentiels pilotés.",
    paint: "#101215",
    vehicle: { src: K + "suv-luxury.glb", kind: "kenney", length: 4.94, width: 2.02 },
    specs: { moteur: "V8 4,4 l biturbo hybride léger", puissance: "625 ch", couple: "750 Nm", zeroCent: "3,9 s", vmax: "290 km/h", poids: "2 385 kg", transmission: "M xDrive, auto 8" },
    sections: [
      { view: "aero", title: "Présence", text: "Les haricots éclairés, les ailes élargies, les quatre sorties d'échappement : rien n'est discret, et c'est le but. Le X5 M occupe la route.", facts: [["Largeur", "2,02 m"], ["Longueur", "4,94 m"]] },
      { view: "wheel", title: "Châssis actif", text: "Barres antiroulis actives, amortisseurs pilotés, différentiel arrière M. Les 2 385 kg se font oublier en courbe, ce qui ne devrait pas être possible.", facts: [["Jantes", "21 / 22 pouces"], ["Freins", "395 mm"]] },
      { view: "rear", title: "V8 S68", text: "Le même V8 que la M5, avec un alterno-démarreur de 48 V qui gomme le turbo lag. 750 Nm disponibles dès 1 800 tr/min.", facts: [["Régime maxi", "7 200 tr/min"], ["Consommation", "12,5 l/100 km"]] },
      { view: "top", title: "Habitacle", text: "Cuir Merino étendu, écran incurvé, sièges M multifonctions chauffants et ventilés. Une pièce à vivre qui accélère.", facts: [["Coffre", "650 l"], ["Écran", "14,9 pouces"]] },
    ],
    drive: { vmax: 290, accel: 12, brake: 12.5, grip: 1.05, mass: 2385 },
  },
  {
    id: "911",
    rank: 7,
    brand: "Porsche",
    model: "911 Carrera GTS",
    tier: "Sportive",
    years: "2024 –",
    origin: "Zuffenhausen, Allemagne",
    price: "≈ 175 000 €",
    tagline: "Soixante ans de la même idée, jamais la même voiture.",
    lead: "Le moteur à l'arrière, la silhouette qu'un enfant dessine, et une évolution continue depuis 1963. La GTS est la première 911 hybride : un turbo électrique qui répond avant que le pied ait fini d'enfoncer la pédale.",
    paint: "#d5d8dc",
    vehicle: { src: Q + "q-sport-a.glb", kind: "quaternius", length: 4.53 },
    specs: { moteur: "6 cyl. à plat 3,6 l T-Hybrid", puissance: "541 ch", couple: "610 Nm", zeroCent: "3,0 s", vmax: "312 km/h", poids: "1 595 kg", transmission: "Propulsion, PDK 8" },
    sections: [
      { view: "aero", title: "Silhouette", text: "Le pare-brise est plus vertical, les ailes bombées, la ligne de toit tombe jusqu'au pare-chocs. La 911 est la seule voiture qu'on reconnaît de n'importe quel angle.", facts: [["Cx", "0,29"], ["Longueur", "4,53 m"]] },
      { view: "wheel", title: "Moteur arrière", text: "Le poids sur les roues motrices donne une motricité en sortie de virage qu'aucune voiture à moteur avant n'égale. L'art de Porsche est de dompter ce que cela implique au freinage.", facts: [["Jantes", "20 / 21 pouces"], ["Répartition", "39 / 61"]] },
      { view: "rear", title: "T-Hybrid", text: "Un turbo unique dont la turbine est assistée par un moteur électrique de 15 ch : pression maximale en 0,8 s. Un second moteur électrique dans la boîte PDK ajoute 150 Nm.", facts: [["Tension", "400 V"], ["Batterie", "1,9 kWh"]] },
      { view: "top", title: "Habitacle", text: "Compte-tours numérique au centre, bouton de démarrage à gauche comme aux 24 Heures du Mans, matériaux sans faute. Deux places, deux petits sièges à l'arrière.", facts: [["Coffre avant", "135 l"], ["Places", "2 + 2"]] },
    ],
    drive: { vmax: 312, accel: 16, brake: 14.5, grip: 1.25, mass: 1595 },
  },
  {
    id: "458",
    rank: 8,
    brand: "Ferrari",
    model: "458 Spider",
    tier: "Supercar",
    years: "2011 – 2015",
    origin: "Maranello, Italie",
    price: "≈ 260 000 €",
    tagline: "Le dernier V8 atmosphérique de Maranello, à ciel ouvert.",
    lead: "570 ch sans turbo, 9 000 tr/min, un toit rigide en aluminium qui se replie en 14 secondes. La 458 est la Ferrari que les collectionneurs désignent comme la fin d'une époque.",
    paint: "#c4121a",
    vehicle: { src: Q + "q-sport-b.glb", kind: "quaternius", length: 4.53 },
    specs: { moteur: "V8 4,5 l atmosphérique", puissance: "570 ch", couple: "540 Nm", zeroCent: "3,4 s", vmax: "320 km/h", poids: "1 430 kg", transmission: "Propulsion, F1 7" },
    sections: [
      { view: "aero", title: "Aérodynamique", text: "Les deux ailettes sous la calandre se déforment à haute vitesse pour réduire la portance, sans commande électronique. Le fond plat et le diffuseur produisent 360 kg d'appui à 200 km/h.", facts: [["Appui à 200 km/h", "360 kg"], ["Cx", "0,33"]] },
      { view: "wheel", title: "Châssis et freinage", text: "Structure en aluminium, jantes de 20 pouces, disques carbone-céramique Brembo de 398 mm à l'avant. E-Diff et F1-Trac pilotés par le même calculateur.", facts: [["Freins avant", "398 mm"], ["Jantes", "20 pouces"]] },
      { view: "rear", title: "Moteur", text: "V8 de 4,5 litres à injection directe, position centrale arrière. 570 ch à 9 000 tr/min : la plus haute puissance spécifique jamais obtenue sur un atmosphérique de série.", facts: [["Régime maxi", "9 000 tr/min"], ["Puissance spécifique", "127 ch/l"]] },
      { view: "top", title: "Habitacle", text: "Toutes les commandes sont sur le volant : clignotants, essuie-glaces, phares, Manettino. Aucun levier derrière le volant hormis les palettes.", facts: [["Toit", "14 s"], ["Places", "2"]] },
    ],
    drive: { vmax: 320, accel: 15, brake: 15, grip: 1.3, mass: 1430 },
  },
  {
    id: "revuelto",
    rank: 9,
    brand: "Lamborghini",
    model: "Revuelto",
    tier: "Supercar hybride",
    years: "2023 –",
    origin: "Sant'Agata Bolognese, Italie",
    price: "≈ 500 000 €",
    tagline: "Un V12, trois moteurs électriques, 1 015 chevaux.",
    lead: "Lamborghini a refusé d'abandonner le V12 atmosphérique. La Revuelto l'entoure de trois moteurs électriques et d'une coque monobloc en carbone. Le résultat est la voiture de série la plus rapide jamais produite par la marque.",
    paint: "#5cc33b",
    vehicle: { src: Q + "q-sport-b.glb", kind: "quaternius", length: 4.95 },
    accent: "#1c1f24",
    specs: { moteur: "V12 6,5 l atmosphérique + 3 électriques", puissance: "1 015 ch", couple: "725 Nm (V12)", zeroCent: "2,5 s", vmax: "350 km/h", poids: "1 772 kg", transmission: "Intégrale, DCT 8" },
    sections: [
      { view: "aero", title: "Forme en Y", text: "Chaque prise d'air, chaque phare, chaque sortie d'échappement dessine un Y. Le capot avant abrite le moteur électrique et un coffre ; la voiture est sculptée par l'air qui la traverse.", facts: [["Appui", "+66 % vs Aventador"], ["Longueur", "4,95 m"]] },
      { view: "wheel", title: "Quatre roues motrices électriques", text: "Deux moteurs à l'avant, un par roue, capables de vectoriser le couple et de faire reculer la voiture sans le V12. Le train arrière reste mécanique.", facts: [["Jantes", "21 / 22 pouces"], ["Freins", "410 mm carbone"]] },
      { view: "rear", title: "V12 L545", text: "Le moteur est tourné de 180° par rapport à l'Aventador, la boîte est derrière lui, transversale. 825 ch pour le seul V12, à 9 250 tr/min.", facts: [["Régime maxi", "9 500 tr/min"], ["Poids moteur", "218 kg"]] },
      { view: "top", title: "Habitacle", text: "Trois écrans, un volant qui regroupe les modes de conduite sur deux molettes, des sièges en carbone. Treize combinaisons de conduite, dont un mode électrique pur.", facts: [["Modes", "13"], ["Autonomie électrique", "10 km"]] },
    ],
    drive: { vmax: 350, accel: 22, brake: 17, grip: 1.45, mass: 1772 },
  },
  {
    id: "chiron",
    rank: 10,
    brand: "Bugatti",
    model: "Chiron Super Sport",
    tier: "Hypercar",
    years: "2021 – 2024",
    origin: "Molsheim, France",
    price: "≈ 3 800 000 €",
    tagline: "Seize cylindres, quatre turbos, 440 km/h. Le sommet.",
    lead: "La Chiron Super Sport est la voiture de série qui a franchi 490 km/h en essais. Chaque exemplaire est assemblé à la main à Molsheim, en Alsace, en six mois. Il y en a eu moins de cent.",
    paint: "#1a2b52",
    accent: "#0f1420",
    vehicle: { src: Q + "q-sport-a.glb", kind: "quaternius", length: 4.79 },
    specs: { moteur: "W16 8,0 l quadri-turbo", puissance: "1 600 ch", couple: "1 600 Nm", zeroCent: "2,4 s", vmax: "440 km/h", poids: "1 995 kg", transmission: "Intégrale, DSG 7" },
    sections: [
      { view: "aero", title: "Longue queue", text: "L'arrière est allongé de 25 cm par rapport à la Chiron pour retarder le décollement de l'air. À 440 km/h, la voiture traverse 122 mètres d'air chaque seconde.", facts: [["Longueur", "4,79 m"], ["Cx", "0,35"]] },
      { view: "wheel", title: "Pneus", text: "Michelin a développé des pneus spécifiques, contrôlés aux rayons X avant montage. Au-delà de 400 km/h, chaque gramme de la bande de roulement subit 3 800 g.", facts: [["Jantes", "20 / 21 pouces"], ["Freins", "420 mm carbone"]] },
      { view: "rear", title: "W16", text: "Seize cylindres en W, huit litres, quatre turbocompresseurs qui s'enclenchent par paires. À plein régime, le moteur avale 60 000 litres d'air par minute.", facts: [["Régime maxi", "7 100 tr/min"], ["Radiateurs", "10"]] },
      { view: "top", title: "Habitacle", text: "Aluminium fraisé, cuir, aucun écran central : la vitesse est affichée sur un cadran mécanique gradué jusqu'à 500. Bugatti refuse les écrans qui vieillissent.", facts: [["Compteur", "500 km/h"], ["Places", "2"]] },
    ],
    drive: { vmax: 420, accel: 24, brake: 17, grip: 1.4, mass: 1995 },
  },
];

export function carById(id) {
  return CARS.find((c) => c.id === id) || CARS[7];
}

export function carFromLocation() {
  const id = new URLSearchParams(location.search).get("car");
  return carById(id || (localStorage.getItem("car") || "458"));
}

export function rememberCar(id) {
  try {
    localStorage.setItem("car", id);
  } catch (e) {
    /* stockage indisponible : on ignore */
  }
}
